spring:
  application:
    name: config
  cloud:
    config:
      server:
        svn:
          uri: svn://127.0.0.1
          username: van
          password: 123456
          default-label: trunk
  profiles:
    active: subversion
   
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6100/eureka/       
      register-with-eureka: true
      fetch-registry: true
      
server:
  port: 7000

